<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_PcjsABJDEe2H27Fazk_mAw" name="ELABORACIÓN Y APROBACIÓN " author="Usuario" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_PcjsARJDEe2H27Fazk_mAw" name="ELABORACIÓN Y APROVACIÓN DEL PROYECTO DE TIC">
      <elements xmi:type="process:Lane" xmi:id="_PcjsAhJDEe2H27Fazk_mAw" name="ESTUDIANTE" actor="_J9xAoBMKEe2ovpqI08AB_w">
        <elements xmi:type="process:StartEvent" xmi:id="_PcjsAxJDEe2H27Fazk_mAw" name="propuesta TIC" outgoing="_PcjsGBJDEe2H27Fazk_mAw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PcjsBBJDEe2H27Fazk_mAw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PcjsBRJDEe2H27Fazk_mAw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PcjsBhJDEe2H27Fazk_mAw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PcjsBxJDEe2H27Fazk_mAw" name="Solicitar aprobacion de trabajo de titulación" outgoing="_1NtvkBL9Ee2ovpqI08AB_w" incoming="_PcjsGBJDEe2H27Fazk_mAw _LqGdEBL-Ee2ovpqI08AB_w" actor="_J9xAoBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PcjsCBJDEe2H27Fazk_mAw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PcjsCRJDEe2H27Fazk_mAw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PcjsChJDEe2H27Fazk_mAw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PcjsCxJDEe2H27Fazk_mAw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PcjsDBJDEe2H27Fazk_mAw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PcjsDRJDEe2H27Fazk_mAw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PcjsDhJDEe2H27Fazk_mAw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PcjsDxJDEe2H27Fazk_mAw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PcjsEBJDEe2H27Fazk_mAw" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_PcjsERJDEe2H27Fazk_mAw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PcjsEhJDEe2H27Fazk_mAw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PcjsExJDEe2H27Fazk_mAw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_A3oHEBMAEe2ovpqI08AB_w" name="Revisar respuesta de pertinencia " outgoing="_knyiUBMBEe2ovpqI08AB_w" incoming="_z_0uMBL_Ee2ovpqI08AB_w" actor="_J9xAoBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z_fXARL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z_fXABL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z_fXAhL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z_fXAxL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z_fXBBL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z_fXBRL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z_fXBxL_Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z_fXBhL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_A3ouKRMAEe2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_A3ouKhMAEe2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_A3ouKBMAEe2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_A3pVMBMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_KIyJYBMAEe2ovpqI08AB_w" name="Solicitar designación director de trabajo de Titulación" outgoing="_ebLEgBMAEe2ovpqI08AB_w" incoming="_2TkScBL_Ee2ovpqI08AB_w _O7WEABMBEe2ovpqI08AB_w" actor="_J9xAoBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2TbIgRL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2TbIgBL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2TbIghL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2TbIgxL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2TbIhBL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2TbIhRL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2TbIhxL_Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2TbIhhL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KIyweRMAEe2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_KIywehMAEe2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KIyweBMAEe2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KIzXgBMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_hL0KsBMBEe2ovpqI08AB_w" name="PTT no aprobado" incoming="_knyiUBMBEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hL0xwRMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hL0xwBMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hL0xwhMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_sOKd0BMBEe2ovpqI08AB_w" name="PTT aprobado" incoming="_x_JlABMBEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sOLE4RMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sOLE4BMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sOLE4hMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_fGO7EBL9Ee2ovpqI08AB_w" name="SECRETARIA" actor="_RCV2oBMKEe2ovpqI08AB_w">
        <elements xmi:type="process:Task" xmi:id="_79v48BL9Ee2ovpqI08AB_w" name="validar documentación y solicitud de aprobación de trabajo de titulación" outgoing="_UTPdIBL-Ee2ovpqI08AB_w" incoming="_1NtvkBL9Ee2ovpqI08AB_w" actor="_RCV2oBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1MnjYBL9Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1Mm8UBL9Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1MnjYRL9Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1MnjYhL9Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1MoKcBL9Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1MoKcRL9Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1MpYkBL9Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1MoxgBL9Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_79yVMBL9Ee2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_79yVMRL9Ee2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_79xuJRL9Ee2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_79yVMhL9Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="__qyLYBL9Ee2ovpqI08AB_w" name="¿documentación solicitud TIC correcta?" outgoing="_DXDBwBL-Ee2ovpqI08AB_w _X5FicBL-Ee2ovpqI08AB_w" incoming="_UTPdIBL-Ee2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__qyycRL9Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__qyycBL9Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__qzZgBL9Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_J96oEBL-Ee2ovpqI08AB_w" name="Notificar documentación incorrecta de propuesta de trabajo de Titulación" outgoing="_LqGdEBL-Ee2ovpqI08AB_w" incoming="_DXDBwBL-Ee2ovpqI08AB_w" actor="_RCV2oBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DWxU8RL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DWxU8BL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DWxU8hL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DWx8ABL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DWx8ARL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DWx8AhL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DWx8BBL-Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DWx8AxL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_J972OBL-Ee2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_J972ORL-Ee2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_J972NxL-Ee2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_J972OhL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_uZbGYBL_Ee2ovpqI08AB_w" name="¿La propuesta es pertinente?" outgoing="_z_0uMBL_Ee2ovpqI08AB_w _2TkScBL_Ee2ovpqI08AB_w" incoming="_slu7MBL_Ee2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_skMqIRL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_skMqIBL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_skMqIhL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_iAHx8BMAEe2ovpqI08AB_w" name="Validar documentación solicitud de designación de director de  PTT" outgoing="_xaTA8BMAEe2ovpqI08AB_w" incoming="_ebLEgBMAEe2ovpqI08AB_w" actor="_RCV2oBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ea-3QRMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ea-3QBMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ea_eUBMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ea_eURMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ea_eUhMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ea_eUxMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ea_eVRMAEe2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ea_eVBMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iAIZCRMAEe2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_iAIZChMAEe2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iAIZCBMAEe2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iAIZCxMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_LyomoBMBEe2ovpqI08AB_w" name="notificación  documentación incorrecta solicitud de designación de director de  PTT" outgoing="_O7WEABMBEe2ovpqI08AB_w" incoming="_52_gcBMAEe2ovpqI08AB_w" actor="_RCV2oBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_52zTMRMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_52zTMBMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_52zTMhMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_52zTMxMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_52zTNBMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_52zTNRMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_52z6QBMAEe2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_52zTNhMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Lyqb1hMBEe2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_Lyqb1xMBEe2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Lyqb1RMBEe2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Lyqb2BMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_NQKUkBMBEe2ovpqI08AB_w" name="¿Documentación solicitud de director correcta" outgoing="_52_gcBMAEe2ovpqI08AB_w _SpHWQBMBEe2ovpqI08AB_w" incoming="_xaTA8BMAEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xaKeEhMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xaKeERMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xaLFIBMAEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_flPyUBL9Ee2ovpqI08AB_w" name="DIRECTOR DE LA CARRERA" actor="_hjyGQB2rEe2et9eyhI92Zw">
        <elements xmi:type="process:Task" xmi:id="_d04ygBL-Ee2ovpqI08AB_w" name="solicitar informe de pertinencia" outgoing="_gnVsABL-Ee2ovpqI08AB_w" incoming="_X5FicBL-Ee2ovpqI08AB_w _2s-GYBL-Ee2ovpqI08AB_w" actor="_SSAuwBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_X4nBURL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_X4nBUBL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_X4nBUhL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_X4nBUxL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_X4nBVBL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_X4nBVRL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_X4nBVxL-Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_X4nBVhL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_d05ZmRL-Ee2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_d05ZmhL-Ee2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_d05ZmBL-Ee2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_d05ZmxL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_uXtEkBL-Ee2ovpqI08AB_w" name="Notificar incumplimiento de informe de pertinencia " outgoing="_2s-GYBL-Ee2ovpqI08AB_w" incoming="_uX5R0BL-Ee2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uXtroBL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uXtEkRL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uXtroRL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uXtrohL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uXtroxL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uXtrpBL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uXtrphL-Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uXtrpRL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SZX8ABL_Ee2ovpqI08AB_w" name="Validar informe de pertinecia " outgoing="_slu7MBL_Ee2ovpqI08AB_w" incoming="_Kg5j4BL_Ee2ovpqI08AB_w _n3VSYBL_Ee2ovpqI08AB_w" actor="_SSAuwBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KgkzwRL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KgkzwBL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KgkzwhL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KgkzwxL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KgkzxBL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KgkzxRL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KgkzxxL_Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KgkzxhL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_XqqPcBL_Ee2ovpqI08AB_w" name="3 días laborables" outgoing="_du5CwBL_Ee2ovpqI08AB_w">
            <condition xmi:type="expression:Expression" xmi:id="_o3WSABMMEe2ovpqI08AB_w" name="3 días: 00:00:00" content="259200000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SZZKJhL_Ee2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_SZZKJxL_Ee2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SZZKJRL_Ee2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SZZKKBL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_dulgwBL_Ee2ovpqI08AB_w" name="recordar validar el inform de pertinencia" outgoing="_n3VSYBL_Ee2ovpqI08AB_w" incoming="_du5CwBL_Ee2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dumH0RL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dumH0BL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dumH0hL_Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dumH0xL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dumH1BL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dumH1RL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dumH1xL_Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dumH1hL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_YNSJcBMBEe2ovpqI08AB_w" text="notificar al director y estudiente "/>
        <elements xmi:type="process:Task" xmi:id="_uvaHABMLEe2ovpqI08AB_w" name="Designar Director de  TT" outgoing="_x_JlABMBEe2ovpqI08AB_w" incoming="_SpHWQBMBEe2ovpqI08AB_w" actor="_SSAuwBMKEe2ovpqI08AB_w">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_YOfqYBMBEe2ovpqI08AB_w" source="_YNSJcBMBEe2ovpqI08AB_w"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_So564RMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_So564BMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_So564hMBEe2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_So564xMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_So565BMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_So565RMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_So565xMBEe2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_So565hMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uvbVIxMLEe2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_uvbVJBMLEe2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uvbVIhMLEe2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uvbVJRMLEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_f2LxUBL9Ee2ovpqI08AB_w" name="DOCENTE ESPECIALISTA" actor="_U0bBIBMKEe2ovpqI08AB_w">
        <elements xmi:type="process:Task" xmi:id="_io5UEBL-Ee2ovpqI08AB_w" name="adjuntar informe de pertinecia " outgoing="_Kg5j4BL_Ee2ovpqI08AB_w" incoming="_gnVsABL-Ee2ovpqI08AB_w" actor="_U0bBIBMKEe2ovpqI08AB_w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gm_twRL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gm_twBL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gm_twhL-Ee2ovpqI08AB_w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gm_twxL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gm_txBL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gm_txRL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gm_txxL-Ee2ovpqI08AB_w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gm_txhL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_pergIBL-Ee2ovpqI08AB_w" name="8 días laborables " outgoing="_uX5R0BL-Ee2ovpqI08AB_w">
            <condition xmi:type="expression:Expression" xmi:id="_fkDFMBMNEe2ovpqI08AB_w" name="8 días: 00:00:01" content="691201000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_io6iORL-Ee2ovpqI08AB_w" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_io6iOhL-Ee2ovpqI08AB_w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_io6iOBL-Ee2ovpqI08AB_w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_io7JQBL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_GLvycBMIEe2ovpqI08AB_w" name="nombre" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_GLvycRMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_JSI7oBMIEe2ovpqI08AB_w" name="apellido" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_JSI7oRMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_MvZFoBMIEe2ovpqI08AB_w" name="fecha" dataType="_PcjsLRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_MvZFoRMIEe2ovpqI08AB_w" content="" returnType="java.util.Date"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_UfwDkBMIEe2ovpqI08AB_w" name="aprobado" dataType="_PcjsLBJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_UfwDkRMIEe2ovpqI08AB_w" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_bD2pwBMIEe2ovpqI08AB_w" name="comentario" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bD2pwRMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_kFHO4BMIEe2ovpqI08AB_w" name="propuestaAprobado" dataType="_PcjsLBJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_kFHO4RMIEe2ovpqI08AB_w" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_sYR-8BMIEe2ovpqI08AB_w" name="estudiante" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_sYR-8RMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_t83-MBMIEe2ovpqI08AB_w" name="secretaria" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_t83-MRMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_vwLu4BMIEe2ovpqI08AB_w" name="gestor" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_vwLu4RMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_x4DaUBMIEe2ovpqI08AB_w" name="docenteespecialista" dataType="_PcjsMRJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_x4DaURMIEe2ovpqI08AB_w" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_MsXfcBMLEe2ovpqI08AB_w" name="directorAsignado" dataType="_PcjsLBJDEe2H27Fazk_mAw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_MsXfcRMLEe2ovpqI08AB_w" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_PcjsFBJDEe2H27Fazk_mAw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_PcjsFRJDEe2H27Fazk_mAw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_PcjsFhJDEe2H27Fazk_mAw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_PcjsFxJDEe2H27Fazk_mAw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PcjsGBJDEe2H27Fazk_mAw" target="_PcjsBxJDEe2H27Fazk_mAw" source="_PcjsAxJDEe2H27Fazk_mAw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PcjsGRJDEe2H27Fazk_mAw"/>
        <condition xmi:type="expression:Expression" xmi:id="_PcjsGhJDEe2H27Fazk_mAw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1NtvkBL9Ee2ovpqI08AB_w" target="_79v48BL9Ee2ovpqI08AB_w" source="_PcjsBxJDEe2H27Fazk_mAw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1Nu9sBL9Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_1NvkwBL9Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DXDBwBL-Ee2ovpqI08AB_w" name="NO" target="_J96oEBL-Ee2ovpqI08AB_w" source="__qyLYBL9Ee2ovpqI08AB_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DXDo0BL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_DXDo0RL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LqGdEBL-Ee2ovpqI08AB_w" target="_PcjsBxJDEe2H27Fazk_mAw" source="_J96oEBL-Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LqHEIBL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_LqHEIRL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UTPdIBL-Ee2ovpqI08AB_w" target="__qyLYBL9Ee2ovpqI08AB_w" source="_79v48BL9Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UTPdIRL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_UTPdIhL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X5FicBL-Ee2ovpqI08AB_w" name="SI" target="_d04ygBL-Ee2ovpqI08AB_w" source="__qyLYBL9Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X5H-sBL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_X5H-sRL-Ee2ovpqI08AB_w" name="aprobado" content="aprobado" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_WUuywBMJEe2ovpqI08AB_w" name="aprobado" dataType="_PcjsLBJDEe2H27Fazk_mAw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gnVsABL-Ee2ovpqI08AB_w" target="_io5UEBL-Ee2ovpqI08AB_w" source="_d04ygBL-Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gnVsARL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_gnVsAhL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uX5R0BL-Ee2ovpqI08AB_w" target="_uXtEkBL-Ee2ovpqI08AB_w" source="_pergIBL-Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uX544BL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_uX544RL-Ee2ovpqI08AB_w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2s-GYBL-Ee2ovpqI08AB_w" target="_d04ygBL-Ee2ovpqI08AB_w" source="_uXtEkBL-Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2s-tcBL-Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_2s_UgBL-Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Kg5j4BL_Ee2ovpqI08AB_w" target="_SZX8ABL_Ee2ovpqI08AB_w" source="_io5UEBL-Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Kg6K8BL_Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Kg6K8RL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_du5CwBL_Ee2ovpqI08AB_w" target="_dulgwBL_Ee2ovpqI08AB_w" source="_XqqPcBL_Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_du7fABL_Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_du7fARL_Ee2ovpqI08AB_w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n3VSYBL_Ee2ovpqI08AB_w" target="_SZX8ABL_Ee2ovpqI08AB_w" source="_dulgwBL_Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_n3VSYRL_Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_n3VSYhL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_slu7MBL_Ee2ovpqI08AB_w" target="_uZbGYBL_Ee2ovpqI08AB_w" source="_SZX8ABL_Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_slu7MRL_Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_slu7MhL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_z_0uMBL_Ee2ovpqI08AB_w" name="NO" target="_A3oHEBMAEe2ovpqI08AB_w" source="_uZbGYBL_Ee2ovpqI08AB_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_z_0uMRL_Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_z_0uMhL_Ee2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2TkScBL_Ee2ovpqI08AB_w" name="SI" target="_KIyJYBMAEe2ovpqI08AB_w" source="_uZbGYBL_Ee2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2TkScRL_Ee2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_2TkSchL_Ee2ovpqI08AB_w" name="propuestaAprobado" content="propuestaAprobado" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_xc558BMJEe2ovpqI08AB_w" name="propuestaAprobado" dataType="_PcjsLBJDEe2H27Fazk_mAw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ebLEgBMAEe2ovpqI08AB_w" target="_iAHx8BMAEe2ovpqI08AB_w" source="_KIyJYBMAEe2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ebLEgRMAEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_ebLrkBMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xaTA8BMAEe2ovpqI08AB_w" target="_NQKUkBMBEe2ovpqI08AB_w" source="_iAHx8BMAEe2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xaTA8RMAEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_xaTA8hMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_52_gcBMAEe2ovpqI08AB_w" name="NO" target="_LyomoBMBEe2ovpqI08AB_w" source="_NQKUkBMBEe2ovpqI08AB_w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_53AukBMAEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_53AukRMAEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_O7WEABMBEe2ovpqI08AB_w" target="_KIyJYBMAEe2ovpqI08AB_w" source="_LyomoBMBEe2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_O7WrEBMBEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_O7WrERMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SpHWQBMBEe2ovpqI08AB_w" name="SI" target="_uvaHABMLEe2ovpqI08AB_w" source="_NQKUkBMBEe2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SpH9UBMBEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_SpH9URMBEe2ovpqI08AB_w" name="directorAsignado" content="directorAsignado" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_i5jTUBMLEe2ovpqI08AB_w" name="directorAsignado" dataType="_PcjsLBJDEe2H27Fazk_mAw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_knyiUBMBEe2ovpqI08AB_w" target="_hL0KsBMBEe2ovpqI08AB_w" source="_A3oHEBMAEe2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_knzJYBMBEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_knzJYRMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x_JlABMBEe2ovpqI08AB_w" target="_sOKd0BMBEe2ovpqI08AB_w" source="_uvaHABMLEe2ovpqI08AB_w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x_KMEBMBEe2ovpqI08AB_w"/>
        <condition xmi:type="expression:Expression" xmi:id="_x_KMERMBEe2ovpqI08AB_w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_J9xAoBMKEe2ovpqI08AB_w" name="estudiante" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_RCV2oBMKEe2ovpqI08AB_w" name="secretaria"/>
      <actors xmi:type="process:Actor" xmi:id="_SSAuwBMKEe2ovpqI08AB_w" name="gestordecarrera"/>
      <actors xmi:type="process:Actor" xmi:id="_U0bBIBMKEe2ovpqI08AB_w" name="docenteEspecialista"/>
      <actors xmi:type="process:Actor" xmi:id="_hjyGQB2rEe2et9eyhI92Zw" name="director"/>
      <contract xmi:type="process:Contract" xmi:id="_PcjsHBJDEe2H27Fazk_mAw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PcjsHRJDEe2H27Fazk_mAw">
        <name xmi:type="expression:Expression" xmi:id="_PcjsHhJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PcjsHxJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PcjsIBJDEe2H27Fazk_mAw">
        <name xmi:type="expression:Expression" xmi:id="_PcjsIRJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PcjsIhJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PcjsIxJDEe2H27Fazk_mAw">
        <name xmi:type="expression:Expression" xmi:id="_PcjsJBJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PcjsJRJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PcjsJhJDEe2H27Fazk_mAw">
        <name xmi:type="expression:Expression" xmi:id="_PcjsJxJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PcjsKBJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_PcjsKRJDEe2H27Fazk_mAw">
        <name xmi:type="expression:Expression" xmi:id="_PcjsKhJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_PcjsKxJDEe2H27Fazk_mAw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_PcjsLBJDEe2H27Fazk_mAw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_PcjsLRJDEe2H27Fazk_mAw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_PcjsLhJDEe2H27Fazk_mAw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_PcjsLxJDEe2H27Fazk_mAw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_PcjsMBJDEe2H27Fazk_mAw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_PcjsMRJDEe2H27Fazk_mAw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_PcjsMhJDEe2H27Fazk_mAw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_PcjsMxJDEe2H27Fazk_mAw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_PcjsNBJDEe2H27Fazk_mAw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_PcjsNRJDEe2H27Fazk_mAw" type="Process" element="_PcjsABJDEe2H27Fazk_mAw" name="MiDiagrama1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_PcjsNhJDEe2H27Fazk_mAw" type="2007" element="_PcjsARJDEe2H27Fazk_mAw">
      <children xmi:type="notation:DecorationNode" xmi:id="_PcjsNxJDEe2H27Fazk_mAw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_PcjsOBJDEe2H27Fazk_mAw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_PcjsORJDEe2H27Fazk_mAw" type="3007" element="_PcjsAhJDEe2H27Fazk_mAw">
          <children xmi:type="notation:DecorationNode" xmi:id="_PcjsOhJDEe2H27Fazk_mAw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_PcjsOxJDEe2H27Fazk_mAw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PcjsPBJDEe2H27Fazk_mAw" type="3005" element="_PcjsBxJDEe2H27Fazk_mAw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PcjsPRJDEe2H27Fazk_mAw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PcjsPhJDEe2H27Fazk_mAw" x="160" y="60" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PcjsPxJDEe2H27Fazk_mAw" type="3002" element="_PcjsAxJDEe2H27Fazk_mAw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PcjsQBJDEe2H27Fazk_mAw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PcjsQRJDEe2H27Fazk_mAw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PcjsQhJDEe2H27Fazk_mAw" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A3pVMRMAEe2ovpqI08AB_w" type="3005" element="_A3oHEBMAEe2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_A3p8QBMAEe2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A3pVMhMAEe2ovpqI08AB_w" x="604" y="95" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KIzXgRMAEe2ovpqI08AB_w" type="3005" element="_KIyJYBMAEe2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KIz-kBMAEe2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KIzXghMAEe2ovpqI08AB_w" x="892" y="96" width="171" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hL31EBMBEe2ovpqI08AB_w" type="3062" element="_hL0KsBMBEe2ovpqI08AB_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hL31EhMBEe2ovpqI08AB_w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hL31ExMBEe2ovpqI08AB_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hL31ERMBEe2ovpqI08AB_w" x="673" y="11"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sOMTABMBEe2ovpqI08AB_w" type="3062" element="_sOKd0BMBEe2ovpqI08AB_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sOM6EBMBEe2ovpqI08AB_w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sOM6ERMBEe2ovpqI08AB_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sOMTARMBEe2ovpqI08AB_w" x="1564" y="151"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_PcjsQxJDEe2H27Fazk_mAw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_PcjsRBJDEe2H27Fazk_mAw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_PcjsRRJDEe2H27Fazk_mAw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_PcjsRhJDEe2H27Fazk_mAw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PcjsRxJDEe2H27Fazk_mAw"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_fGuDQBL9Ee2ovpqI08AB_w" type="3007" element="_fGO7EBL9Ee2ovpqI08AB_w">
          <children xmi:type="notation:DecorationNode" xmi:id="_fGvRYBL9Ee2ovpqI08AB_w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fGv4cBL9Ee2ovpqI08AB_w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_79y8QBL9Ee2ovpqI08AB_w" type="3005" element="_79v48BL9Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_790KYBL9Ee2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_79y8QRL9Ee2ovpqI08AB_w" x="169" y="47" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__q11wBL9Ee2ovpqI08AB_w" type="3008" element="__qyLYBL9Ee2ovpqI08AB_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__q2c0BL9Ee2ovpqI08AB_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__q2c0RL9Ee2ovpqI08AB_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__q11wRL9Ee2ovpqI08AB_w" x="231" y="195"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_J98dQBL-Ee2ovpqI08AB_w" type="3005" element="_J96oEBL-Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_J99EUBL-Ee2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J98dQRL-Ee2ovpqI08AB_w" x="393" y="176" width="176" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uZdioxL_Ee2ovpqI08AB_w" type="3008" element="_uZbGYBL_Ee2ovpqI08AB_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_uZeJsRL_Ee2ovpqI08AB_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_uZeJshL_Ee2ovpqI08AB_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uZeJsBL_Ee2ovpqI08AB_w" x="731" y="164" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iAJAEBMAEe2ovpqI08AB_w" type="3005" element="_iAHx8BMAEe2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iAJnIBMAEe2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iAJAERMAEe2ovpqI08AB_w" x="1315" y="113" width="165" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LyrC4BMBEe2ovpqI08AB_w" type="3005" element="_LyomoBMBEe2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_LyrC4hMBEe2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LyrC4RMBEe2ovpqI08AB_w" x="1029" y="232" width="194" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NQLisBMBEe2ovpqI08AB_w" type="3008" element="_NQKUkBMBEe2ovpqI08AB_w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NQMJwBMBEe2ovpqI08AB_w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NQMJwRMBEe2ovpqI08AB_w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NQLisRMBEe2ovpqI08AB_w" x="1352" y="252" width="42" height="42"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fGuDQRL9Ee2ovpqI08AB_w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fGuDQhL9Ee2ovpqI08AB_w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fGuDQxL9Ee2ovpqI08AB_w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fGv4cRL9Ee2ovpqI08AB_w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fGuDRBL9Ee2ovpqI08AB_w" x="23" y="250" width="1402" height="424"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_flRngBL9Ee2ovpqI08AB_w" type="3007" element="_flPyUBL9Ee2ovpqI08AB_w">
          <children xmi:type="notation:DecorationNode" xmi:id="_flS1oBL9Ee2ovpqI08AB_w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_flTcsBL9Ee2ovpqI08AB_w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_d06AoBL-Ee2ovpqI08AB_w" type="3005" element="_d04ygBL-Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d06nsBL-Ee2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_d06AoRL-Ee2ovpqI08AB_w" x="192" y="50" width="146" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uXvg0BL-Ee2ovpqI08AB_w" type="3027" element="_uXtEkBL-Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uXwH4BL-Ee2ovpqI08AB_w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uXvg0RL-Ee2ovpqI08AB_w" x="441" y="48" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SZZKKRL_Ee2ovpqI08AB_w" type="3005" element="_SZX8ABL_Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SZZxMRL_Ee2ovpqI08AB_w" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_XqrdkBL_Ee2ovpqI08AB_w" type="3043" element="_XqqPcBL_Ee2ovpqI08AB_w" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_XqsEoBL_Ee2ovpqI08AB_w" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_XqsEoRL_Ee2ovpqI08AB_w" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XqrdkRL_Ee2ovpqI08AB_w" x="38" y="68"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SZZxMBL_Ee2ovpqI08AB_w" x="631" y="48" width="154" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dun9ABL_Ee2ovpqI08AB_w" type="3027" element="_dulgwBL_Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dun9AhL_Ee2ovpqI08AB_w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dun9ARL_Ee2ovpqI08AB_w" x="894" y="52" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_YNTXkBMBEe2ovpqI08AB_w" type="3015" element="_YNSJcBMBEe2ovpqI08AB_w">
              <children xmi:type="notation:DecorationNode" xmi:id="_YNT-oBMBEe2ovpqI08AB_w" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_YNTXkRMBEe2ovpqI08AB_w"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_YNTXkhMBEe2ovpqI08AB_w" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_YNTXkxMBEe2ovpqI08AB_w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YNTXlBMBEe2ovpqI08AB_w" x="1125" y="66" width="136" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uvbVJhMLEe2ovpqI08AB_w" type="3005" element="_uvaHABMLEe2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uvb8MBMLEe2ovpqI08AB_w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uvbVJxMLEe2ovpqI08AB_w" x="1327" y="76" width="125" height="62"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_flRngRL9Ee2ovpqI08AB_w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_flSOkBL9Ee2ovpqI08AB_w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_flSOkRL9Ee2ovpqI08AB_w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_flTcsRL9Ee2ovpqI08AB_w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_flSOkhL9Ee2ovpqI08AB_w" x="23" y="674" width="1693" height="284"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_f2NmgBL9Ee2ovpqI08AB_w" type="3007" element="_f2LxUBL9Ee2ovpqI08AB_w">
          <children xmi:type="notation:DecorationNode" xmi:id="_f2ONkBL9Ee2ovpqI08AB_w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_f2ONkRL9Ee2ovpqI08AB_w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_io7JQRL-Ee2ovpqI08AB_w" type="3005" element="_io5UEBL-Ee2ovpqI08AB_w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_io7wUBL-Ee2ovpqI08AB_w" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_pet8YBL-Ee2ovpqI08AB_w" type="3043" element="_pergIBL-Ee2ovpqI08AB_w" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_peujcBL-Ee2ovpqI08AB_w" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_peujcRL-Ee2ovpqI08AB_w" x="8" y="-57"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pet8YRL-Ee2ovpqI08AB_w" x="101" y="-17"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_io7JQhL-Ee2ovpqI08AB_w" x="384" y="75" width="144" height="72"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_f2NmgRL9Ee2ovpqI08AB_w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_f2NmghL9Ee2ovpqI08AB_w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_f2NmgxL9Ee2ovpqI08AB_w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_f2ONkhL9Ee2ovpqI08AB_w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f2NmhBL9Ee2ovpqI08AB_w" x="23" y="958" width="1693" height="248"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_PcjsSBJDEe2H27Fazk_mAw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_PcjsSRJDEe2H27Fazk_mAw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_PcjsShJDEe2H27Fazk_mAw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_PcjsSxJDEe2H27Fazk_mAw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PcjsTBJDEe2H27Fazk_mAw" width="1716" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_PcjsTRJDEe2H27Fazk_mAw"/>
    <edges xmi:type="notation:Connector" xmi:id="_PcjsThJDEe2H27Fazk_mAw" type="4001" element="_PcjsGBJDEe2H27Fazk_mAw" source="_PcjsPxJDEe2H27Fazk_mAw" target="_PcjsPBJDEe2H27Fazk_mAw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PcjsTxJDEe2H27Fazk_mAw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PcjsUBJDEe2H27Fazk_mAw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PcjsURJDEe2H27Fazk_mAw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PcjsUhJDEe2H27Fazk_mAw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1N1rYBL9Ee2ovpqI08AB_w" type="4001" element="_1NtvkBL9Ee2ovpqI08AB_w" source="_PcjsPBJDEe2H27Fazk_mAw" target="_79y8QBL9Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1N3gkBL9Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1N3gkRL9Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1N1rYRL9Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1N1rYhL9Ee2ovpqI08AB_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DXV8sBL-Ee2ovpqI08AB_w" type="4001" element="_DXDBwBL-Ee2ovpqI08AB_w" source="__q11wBL9Ee2ovpqI08AB_w" target="_J98dQBL-Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DXXx4BL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DXXx4RL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DXV8sRL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DXV8shL-Ee2ovpqI08AB_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LqKugBL-Ee2ovpqI08AB_w" type="4001" element="_LqGdEBL-Ee2ovpqI08AB_w" source="_J98dQBL-Ee2ovpqI08AB_w" target="_PcjsPBJDEe2H27Fazk_mAw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LqLVkBL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LqLVkRL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LqKugRL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LqKughL-Ee2ovpqI08AB_w" points="[-72, -24, 231, 338]$[-72, -366, 231, -4]$[-269, -366, 34, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LqVtoBL-Ee2ovpqI08AB_w" id="(1.0,0.2727272727272727)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LqVtoRL-Ee2ovpqI08AB_w" id="(0.7571428571428571,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UTRSUBL-Ee2ovpqI08AB_w" type="4001" element="_UTPdIBL-Ee2ovpqI08AB_w" source="_79y8QBL9Ee2ovpqI08AB_w" target="__q11wBL9Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UTR5YBL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UTR5YRL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UTRSURL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UTRSUhL-Ee2ovpqI08AB_w" points="[-102, 59, 8, -61]$[-102, 116, 8, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UTWK0BL-Ee2ovpqI08AB_w" id="(1.0,0.358695652173913)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UTWK0RL-Ee2ovpqI08AB_w" id="(0.27906976744186046,0.11627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X5gZMBL-Ee2ovpqI08AB_w" type="4001" element="_X5FicBL-Ee2ovpqI08AB_w" source="__q11wBL9Ee2ovpqI08AB_w" target="_d06AoBL-Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X5hAQBL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X5hnUBL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X5gZMRL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X5gZMhL-Ee2ovpqI08AB_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gnW6IBL-Ee2ovpqI08AB_w" type="4001" element="_gnVsABL-Ee2ovpqI08AB_w" source="_d06AoBL-Ee2ovpqI08AB_w" target="_io7JQRL-Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gnXhMBL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gnXhMRL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gnW6IRL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gnW6IhL-Ee2ovpqI08AB_w" points="[-34, 36, -225, -191]$[-34, 227, -225, 0]$[119, 227, -72, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uX8VIBL-Ee2ovpqI08AB_w" type="4001" element="_uX5R0BL-Ee2ovpqI08AB_w" source="_pet8YBL-Ee2ovpqI08AB_w" target="_uXvg0BL-Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uX88MBL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uX88MRL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uX8VIRL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uX8VIhL-Ee2ovpqI08AB_w" points="[0, -12, -20, 175]$[0, -151, -20, 36]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2tAioBL-Ee2ovpqI08AB_w" type="4001" element="_2s-GYBL-Ee2ovpqI08AB_w" source="_uXvg0BL-Ee2ovpqI08AB_w" target="_d06AoBL-Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2tH3YBL-Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2tH3YRL-Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2tAioRL-Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2tAiohL-Ee2ovpqI08AB_w" points="[-75, -4, 100, 6]$[-155, -13, 20, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2tNW8BL-Ee2ovpqI08AB_w" id="(1.0,0.64)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2tNW8RL-Ee2ovpqI08AB_w" id="(0.815068493150685,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Kg8AIBL_Ee2ovpqI08AB_w" type="4001" element="_Kg5j4BL_Ee2ovpqI08AB_w" source="_io7JQRL-Ee2ovpqI08AB_w" target="_SZZKKRL_Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Kg9OQBL_Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Kg9OQRL_Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Kg8nMBL_Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Kg8nMRL_Ee2ovpqI08AB_w" points="[72, 9, -201, 223]$[251, 9, -22, 223]$[251, -176, -22, 38]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_du8tIBL_Ee2ovpqI08AB_w" type="4001" element="_du5CwBL_Ee2ovpqI08AB_w" source="_XqrdkBL_Ee2ovpqI08AB_w" target="_dun9ABL_Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_du8tIxL_Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_du9UMBL_Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_du8tIRL_Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_du8tIhL_Ee2ovpqI08AB_w" points="[13, -6, -196, 34]$[137, -6, -72, 34]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_n3WggBL_Ee2ovpqI08AB_w" type="4001" element="_n3VSYBL_Ee2ovpqI08AB_w" source="_dun9ABL_Ee2ovpqI08AB_w" target="_SZZKKRL_Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n3XHkBL_Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n3XHkRL_Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n3WggRL_Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n3WgghL_Ee2ovpqI08AB_w" points="[-108, -9, 97, 7]$[-193, -22, 12, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_n3bZABL_Ee2ovpqI08AB_w" id="(1.0,0.3611111111111111)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_n3bZARL_Ee2ovpqI08AB_w" id="(0.8701298701298701,0.10526315789473684)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_slwJUBL_Ee2ovpqI08AB_w" type="4001" element="_slu7MBL_Ee2ovpqI08AB_w" source="_SZZKKRL_Ee2ovpqI08AB_w" target="_uZdioxL_Ee2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_slwwYBL_Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_slwwYRL_Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_slwJURL_Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_slwJUhL_Ee2ovpqI08AB_w" points="[36, -38, -9, 178]$[36, -108, -9, 108]$[41, -108, -4, 108]$[41, -199, -4, 17]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_z_18UBL_Ee2ovpqI08AB_w" type="4001" element="_z_0uMBL_Ee2ovpqI08AB_w" source="_uZdioxL_Ee2ovpqI08AB_w" target="_A3pVMRMAEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_z_18UxL_Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_z_2jYBL_Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_z_18URL_Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z_18UhL_Ee2ovpqI08AB_w" points="[-21, 0, 76, 314]$[-84, 0, 13, 314]$[-84, -289, 13, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2T1_QBL_Ee2ovpqI08AB_w" type="4001" element="_2TkScBL_Ee2ovpqI08AB_w" source="_uZdioxL_Ee2ovpqI08AB_w" target="_KIzXgRMAEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2T2mUBL_Ee2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2T2mURL_Ee2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2T1_QRL_Ee2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2T1_QhL_Ee2ovpqI08AB_w" points="[22, 0, -141, 308]$[87, 0, -76, 308]$[87, -308, -76, 0]$[113, -308, -50, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ebNgwBMAEe2ovpqI08AB_w" type="4001" element="_ebLEgBMAEe2ovpqI08AB_w" source="_KIzXgRMAEe2ovpqI08AB_w" target="_iAJAEBMAEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ebNgwxMAEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ebOH0BMAEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ebNgwRMAEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ebNgwhMAEe2ovpqI08AB_w" points="[86, 0, -128, -258]$[204, 0, -10, -258]$[204, 233, -10, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xaUPEBMAEe2ovpqI08AB_w" type="4001" element="_xaTA8BMAEe2ovpqI08AB_w" source="_iAJAEBMAEe2ovpqI08AB_w" target="_NQLisBMBEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xaU2IBMAEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xaU2IRMAEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xaUPERMAEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xaUPEhMAEe2ovpqI08AB_w" points="[-17, 41, -1, -65]$[-17, 86, -1, -20]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_53BVoBMAEe2ovpqI08AB_w" type="4001" element="_52_gcBMAEe2ovpqI08AB_w" source="_NQLisBMBEe2ovpqI08AB_w" target="_LyrC4BMBEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_53B8sBMAEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_53B8sRMAEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_53BVoRMAEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_53BVohMAEe2ovpqI08AB_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_O7XSIBMBEe2ovpqI08AB_w" type="4001" element="_O7WEABMBEe2ovpqI08AB_w" source="_LyrC4BMBEe2ovpqI08AB_w" target="_KIzXgRMAEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_O7X5MBMBEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_O7X5MRMBEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_O7XSIRMBEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_O7XSIhMBEe2ovpqI08AB_w" points="[-136, -28, 110, 344]$[-136, -179, 110, 193]$[-218, -179, 28, 193]$[-218, -330, 28, 42]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_O7cKoBMBEe2ovpqI08AB_w" id="(1.0,0.2916666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SpV_wBMBEe2ovpqI08AB_w" type="4001" element="_SpHWQBMBEe2ovpqI08AB_w" source="_NQLisBMBEe2ovpqI08AB_w" target="_uvbVJhMLEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SpWm0BMBEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SpWm0RMBEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SpV_wRMBEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SpV_whMBEe2ovpqI08AB_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YOiGoBMBEe2ovpqI08AB_w" type="4003" element="_YOfqYBMBEe2ovpqI08AB_w" source="_YNTXkBMBEe2ovpqI08AB_w" target="_uvbVJhMLEe2ovpqI08AB_w">
      <styles xmi:type="notation:FontStyle" xmi:id="_YOiGoRMBEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YOiGohMBEe2ovpqI08AB_w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_knzwcBMBEe2ovpqI08AB_w" type="4001" element="_knyiUBMBEe2ovpqI08AB_w" source="_A3pVMRMAEe2ovpqI08AB_w" target="_hL31EBMBEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kn0XgBMBEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kn0XgRMBEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_knzwcRMBEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_knzwchMBEe2ovpqI08AB_w" points="[-82, -27, 11, 66]$[-82, -82, 11, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kn5QABMBEe2ovpqI08AB_w" id="(1.0,0.32142857142857145)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kn5QARMBEe2ovpqI08AB_w" id="(0.2,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x_KzIBMBEe2ovpqI08AB_w" type="4001" element="_x_JlABMBEe2ovpqI08AB_w" source="_uvbVJhMLEe2ovpqI08AB_w" target="_sOMTABMBEe2ovpqI08AB_w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x_LaMBMBEe2ovpqI08AB_w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x_LaMRMBEe2ovpqI08AB_w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x_KzIRMBEe2ovpqI08AB_w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x_KzIhMBEe2ovpqI08AB_w" points="[0, 0, -95, 462]$[93, -452, -2, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x_PEkBMBEe2ovpqI08AB_w" id="(1.0,0.5079365079365079)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
