<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_TiD3wB2GEe2Zq6PeUF1h1Q" name="PRESENTACIÓN DEL INFORME DE INVESTIGACIÓN" author="Usuario" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_TiD3wR2GEe2Zq6PeUF1h1Q" name="SUSTENTACIÓN PÚBLICA DEL TRABAJO DE TITULACIÓN">
      <elements xmi:type="process:Lane" xmi:id="_TiD3wh2GEe2Zq6PeUF1h1Q" name="Estudiante" actor="_TiD32x2GEe2Zq6PeUF1h1Q">
        <elements xmi:type="process:StartEvent" xmi:id="_TiD3wx2GEe2Zq6PeUF1h1Q" name="Sustentación Pública " outgoing="_TiD32B2GEe2Zq6PeUF1h1Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TiD3xB2GEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TiD3xR2GEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TiD3xh2GEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TiD3xx2GEe2Zq6PeUF1h1Q" name="Solicitar sustentación del TIC O TT " outgoing="_RWlscB2LEe2Zq6PeUF1h1Q" incoming="_TiD32B2GEe2Zq6PeUF1h1Q _xOrfYB2LEe2Zq6PeUF1h1Q _AvaUACMLEe2iQNEGxapAdw _aaMLACTKEe2m-7ZXPv_XKw" actor="_TiD32x2GEe2Zq6PeUF1h1Q">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_LvkZkB2LEe2Zq6PeUF1h1Q" source="_LvZacB2LEe2Zq6PeUF1h1Q"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TiD3yB2GEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TiD3yR2GEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TiD3yh2GEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TiD3yx2GEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TiD3zB2GEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TiD3zR2GEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TiD3zh2GEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TiD3zx2GEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TiD30B2GEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_TiD30R2GEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TiD30h2GEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TiD30x2GEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_LvZacB2LEe2Zq6PeUF1h1Q" text="informe de Aptitud legal Aprobado con las siguientes documentos &#xD;&#xA;1)Record académico legalizado por el Secretario/a-Abogado/a de la Facultad&#xD;&#xA;2)Certificado de la carrera de haber cumplido con el número de horas de  prácticas pre profesionales&#xD;&#xA;3) Certificado de aprobación del Nivel de suficiencia B1 del Marco Común Europeo de Referencia para las Lenguas&#xD;&#xA;4) Certificado del director de trabajo de integración curricular o de titulación, de culminación y aprobación de la opción de titulación&#xD;&#xA;5) Certificado de Tesorería de no adeudar a la Institución&#xD;&#xA;"/>
        <elements xmi:type="process:Task" xmi:id="_pLNYMB2LEe2Zq6PeUF1h1Q" name="Notificar documentación incorrecta" outgoing="_xOrfYB2LEe2Zq6PeUF1h1Q" incoming="_nn-D0B2LEe2Zq6PeUF1h1Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nnEr8B2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nnEE4B2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nnEr8R2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nnEr8h2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nnEr8x2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nnEr9B2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nnEr9h2LEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nnEr9R2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pLPNYx2LEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_pLPNZB2LEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pLPNYh2LEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pLPNZR2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mNyr8CMJEe2iQNEGxapAdw" name="segunda sustentación en 30 días a partir de la primera " outgoing="_AvaUACMLEe2iQNEGxapAdw _MtzwACTJEe2m-7ZXPv_XKw" incoming="_D9iNMCTJEe2m-7ZXPv_XKw _pGKzECTREe2m-7ZXPv_XKw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XNLzgiMJEe2iQNEGxapAdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XNLzgSMJEe2iQNEGxapAdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XNLzgyMJEe2iQNEGxapAdw" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_3cptQCTNEe2m-7ZXPv_XKw" name="fecha2" dataType="_TiD37R2GEe2Zq6PeUF1h1Q">
            <defaultValue xmi:type="expression:Expression" xmi:id="_3cptQSTNEe2m-7ZXPv_XKw" content="" returnType="java.util.Date"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XNLzhCMJEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XNLzhSMJEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XNLzhiMJEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XNLziCMJEe2iQNEGxapAdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XNLzhyMJEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_utzmcCTQEe2m-7ZXPv_XKw" name="Boundary Temporizador1" outgoing="_pGKzECTREe2m-7ZXPv_XKw">
            <condition xmi:type="expression:Expression" xmi:id="_wfJBMCTQEe2m-7ZXPv_XKw" name="30 días: 00:00:00" content="2592000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mNyr-iMJEe2iQNEGxapAdw" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_mNyr-yMJEe2iQNEGxapAdw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mNyr-SMJEe2iQNEGxapAdw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mNyr_CMJEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0mfk0CSTEe2m-7ZXPv_XKw" name="tercera sutentacion en 90 días a partir de la segunda sustentación" outgoing="_N3AeoCTHEe2m-7ZXPv_XKw _aaMLACTKEe2m-7ZXPv_XKw" incoming="_lzQKcCTJEe2m-7ZXPv_XKw _u4bFkCTREe2m-7ZXPv_XKw" actor="_TiD32x2GEe2Zq6PeUF1h1Q">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_TakN0CTHEe2m-7ZXPv_XKw" source="_TaRS4CTHEe2m-7ZXPv_XKw"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yVM3oiSTEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yVM3oSSTEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yVM3oySTEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yVM3pCSTEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yVWooCSTEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yVWooSSTEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yVWooySTEe2m-7ZXPv_XKw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yVWooiSTEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_uIZW0CTREe2m-7ZXPv_XKw" name="Boundary Temporizador2" outgoing="_u4bFkCTREe2m-7ZXPv_XKw">
            <condition xmi:type="expression:Expression" xmi:id="_xvk44CTREe2m-7ZXPv_XKw" name="90 días: 00:00:00" content="7776000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0mfk2iSTEe2m-7ZXPv_XKw" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_0mfk2ySTEe2m-7ZXPv_XKw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0mfk2SSTEe2m-7ZXPv_XKw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0mfk3CSTEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_MKq4oCTHEe2m-7ZXPv_XKw" name="Fin1" incoming="_N3AeoCTHEe2m-7ZXPv_XKw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MKq4oiTHEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MKq4oSTHEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MKq4oyTHEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_TaRS4CTHEe2m-7ZXPv_XKw" text="Si el postulante no obtiene la calificación mínima de siete (7) sobre diez (10) puntos en la tercera sustentación ante el mismo tribunal, no tendrá otra opción de grado y podrá homologar sus estudios en otra carrera o en la misma, aprobando los dos últimos ciclos"/>
        <elements xmi:type="process:XORGateway" xmi:id="_ul1P0CTIEe2m-7ZXPv_XKw" name="¿nota menor a 7/10?" outgoing="_lzQKcCTJEe2m-7ZXPv_XKw" incoming="_MtzwACTJEe2m-7ZXPv_XKw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g7R-cSSTEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g7R-cCSTEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g7R-ciSTEe2m-7ZXPv_XKw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_jPVzgB2HEe2Zq6PeUF1h1Q" name="Secretaria" actor="_YcDTACMMEe2iQNEGxapAdw">
        <elements xmi:type="process:XORGateway" xmi:id="_kFFy8B2LEe2Zq6PeUF1h1Q" name="¿documentación correcta?" outgoing="_nn-D0B2LEe2Zq6PeUF1h1Q _23WYEB2LEe2Zq6PeUF1h1Q" incoming="_aRrF8CMOEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kFGaAR2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kFGaAB2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kFGaAh2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_oZfnYB2LEe2Zq6PeUF1h1Q" name="Revisar Documentación" outgoing="_aRrF8CMOEe2iQNEGxapAdw" incoming="_RWlscB2LEe2Zq6PeUF1h1Q" actor="_YcDTACMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RWJAgB2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RWF9MB2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RWJAgR2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RWJAgh2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RWJAgx2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RWJnkB2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RWJnkh2LEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RWJnkR2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_oZiDoh2LEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_oZiDox2LEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_oZiDoR2LEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_oZiDpB2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_whe-AB2SEe2Zq6PeUF1h1Q" name="Revisar Acta de Grado y documentos" outgoing="_fzBOoCMOEe2iQNEGxapAdw" incoming="_vSpMUB2SEe2Zq6PeUF1h1Q" actor="_YcDTACMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vSfbUh2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vSfbUR2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vSfbUx2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vSfbVB2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vSfbVR2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vSfbVh2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vSfbWB2SEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vSfbVx2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_whoH8R2SEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_whoH8h2SEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_whoH8B2SEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_whoH8x2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_DPhxgB2TEe2Zq6PeUF1h1Q" name="Sustentación de TIC Aprobada " incoming="_SVMw4CMJEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DPhxgh2TEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DPhxgR2TEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DPhxgx2TEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_F5ihcCMJEe2iQNEGxapAdw" name="¿calificacion mayor a 7/10?" outgoing="_SVMw4CMJEe2iQNEGxapAdw _D9iNMCTJEe2m-7ZXPv_XKw" incoming="_fzBOoCMOEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F5ihciMJEe2iQNEGxapAdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F5ihcSMJEe2iQNEGxapAdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F5ihcyMJEe2iQNEGxapAdw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_jwL2wB2HEe2Zq6PeUF1h1Q" name="Director de la Carrera " actor="_cXCh4CMMEe2iQNEGxapAdw">
        <elements xmi:type="process:Task" xmi:id="_3aQQ0B2LEe2Zq6PeUF1h1Q" name="Designar tribunal, fecha y hora de sustentación de TIC" outgoing="_291L0B2REe2Zq6PeUF1h1Q" incoming="_23WYEB2LEe2Zq6PeUF1h1Q" actor="_cXCh4CMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_23MnER2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_23MnEB2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_23MnEh2LEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_23MnEx2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_23MnFB2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_23MnFR2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_23MnFx2LEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_23MnFh2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3aQQ2h2LEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_3aQQ2x2LEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3aQQ2R2LEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3aQQ3B2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_2iPAgB2HEe2Zq6PeUF1h1Q" name="Tribunal" actor="_gOIvQCMMEe2iQNEGxapAdw">
        <elements xmi:type="process:Task" xmi:id="_FFWyEB2QEe2Zq6PeUF1h1Q" name="Revisar Solicitud y ejemplares del TIC por parte de presidente y los dos vocales  " outgoing="_QId6MB2QEe2Zq6PeUF1h1Q" incoming="_291L0B2REe2Zq6PeUF1h1Q" actor="_gOIvQCMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XoS-QR2PEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XoS-QB2PEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XoS-Qh2PEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XoS-Qx2PEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XoS-RB2PEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XoS-RR2PEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XoS-Rx2PEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XoS-Rh2PEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_FFWyGh2QEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_FFWyGx2QEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_FFWyGR2QEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_FFWyHB2QEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_FefY4B2SEe2Zq6PeUF1h1Q" name="Asignar calificacion de  TIC por parte del presidente y vocales " outgoing="_LVfogB2SEe2Zq6PeUF1h1Q" incoming="_QId6MB2QEe2Zq6PeUF1h1Q" actor="_gOIvQCMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QIUwQh2QEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QIUwQR2QEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QIUwQx2QEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QIUwRB2QEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QIUwRR2QEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QIUwRh2QEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QIUwSB2QEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QIUwRx2QEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_FefY6h2SEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_FefY6x2SEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_FefY6R2SEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_FefY7B2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_LVWekB2SEe2Zq6PeUF1h1Q" name="Calcular el promedio de Sustentación de TIC" outgoing="_Z7WpMB2TEe2Zq6PeUF1h1Q" incoming="_LVfogB2SEe2Zq6PeUF1h1Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LVWekh2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LVWekR2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LVWekx2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LVWelB2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LVWelR2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LVWelh2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LVWemB2SEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LVWelx2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_VIfMkB2SEe2Zq6PeUF1h1Q" name="Firmar acta de sutentación Pública por parte del presidente, vocales y estudiente" outgoing="_vSpMUB2SEe2Zq6PeUF1h1Q" incoming="_fk1aMB2TEe2Zq6PeUF1h1Q" actor="_gOIvQCMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UkknMh2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UkknMR2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UkknMx2SEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UkknNB2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UkknNR2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UkknNh2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UkknOB2SEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UkknNx2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_VIfMmh2SEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_VIfMmx2SEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_VIfMmR2SEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_VIfMnB2SEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_66wf8B2HEe2Zq6PeUF1h1Q" name="Secretario abaogado" actor="_iWY1MCMMEe2iQNEGxapAdw">
        <elements xmi:type="process:Task" xmi:id="_evCaoB2TEe2Zq6PeUF1h1Q" name="Levantar Acta" outgoing="_fk1aMB2TEe2Zq6PeUF1h1Q" incoming="_Z7WpMB2TEe2Zq6PeUF1h1Q" actor="_iWY1MCMMEe2iQNEGxapAdw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Z7Rwsh2TEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Z7RwsR2TEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Z7Rwsx2TEe2Zq6PeUF1h1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Z7RwtB2TEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Z7RwtR2TEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Z7Rwth2TEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Z7RwuB2TEe2Zq6PeUF1h1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Z7Rwtx2TEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_evCaqh2TEe2Zq6PeUF1h1Q" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_evCaqx2TEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_evCaqR2TEe2Zq6PeUF1h1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_evCarB2TEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_6CXs4CMNEe2iQNEGxapAdw" name="estudiante" dataType="_TiD38R2GEe2Zq6PeUF1h1Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CXs4SMNEe2iQNEGxapAdw" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_C5thACMOEe2iQNEGxapAdw" name="documentosCorrectos" dataType="_TiD37B2GEe2Zq6PeUF1h1Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_C5thASMOEe2iQNEGxapAdw" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_nztHkCMOEe2iQNEGxapAdw" name="notaMayorDe7" dataType="_TiD37B2GEe2Zq6PeUF1h1Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_nz24kCMOEe2iQNEGxapAdw" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_ekiZoCTMEe2m-7ZXPv_XKw" name="primera" dataType="_TiD37R2GEe2Zq6PeUF1h1Q">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ekiZoSTMEe2m-7ZXPv_XKw" content="" returnType="java.util.Date"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_TiD31B2GEe2Zq6PeUF1h1Q" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_TiD31R2GEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_TiD31h2GEe2Zq6PeUF1h1Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_TiD31x2GEe2Zq6PeUF1h1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TiD32B2GEe2Zq6PeUF1h1Q" target="_TiD3xx2GEe2Zq6PeUF1h1Q" source="_TiD3wx2GEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TiD32R2GEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_TiD32h2GEe2Zq6PeUF1h1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RWlscB2LEe2Zq6PeUF1h1Q" target="_oZfnYB2LEe2Zq6PeUF1h1Q" source="_TiD3xx2GEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RWp94B2LEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_RWp94R2LEe2Zq6PeUF1h1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nn-D0B2LEe2Zq6PeUF1h1Q" name="NO" target="_pLNYMB2LEe2Zq6PeUF1h1Q" source="_kFFy8B2LEe2Zq6PeUF1h1Q" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nn-q4B2LEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_nn-q4R2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xOrfYB2LEe2Zq6PeUF1h1Q" target="_TiD3xx2GEe2Zq6PeUF1h1Q" source="_pLNYMB2LEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xOrfYR2LEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_xOrfYh2LEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_23WYEB2LEe2Zq6PeUF1h1Q" name="SI" target="_3aQQ0B2LEe2Zq6PeUF1h1Q" source="_kFFy8B2LEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_23WYER2LEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_23WYEh2LEe2Zq6PeUF1h1Q" name="documentosCorrectos" content="documentosCorrectos" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_MoCngCMOEe2iQNEGxapAdw" name="documentosCorrectos" dataType="_TiD37B2GEe2Zq6PeUF1h1Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QId6MB2QEe2Zq6PeUF1h1Q" target="_FefY4B2SEe2Zq6PeUF1h1Q" source="_FFWyEB2QEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QId6MR2QEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_QId6Mh2QEe2Zq6PeUF1h1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_291L0B2REe2Zq6PeUF1h1Q" target="_FFWyEB2QEe2Zq6PeUF1h1Q" source="_3aQQ0B2LEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_291L0R2REe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_291L0h2REe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LVfogB2SEe2Zq6PeUF1h1Q" target="_LVWekB2SEe2Zq6PeUF1h1Q" source="_FefY4B2SEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LVfogR2SEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_LVfogh2SEe2Zq6PeUF1h1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vSpMUB2SEe2Zq6PeUF1h1Q" target="_whe-AB2SEe2Zq6PeUF1h1Q" source="_VIfMkB2SEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vSpMUR2SEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_vSpMUh2SEe2Zq6PeUF1h1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Z7WpMB2TEe2Zq6PeUF1h1Q" target="_evCaoB2TEe2Zq6PeUF1h1Q" source="_LVWekB2SEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Z7WpMR2TEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_Z7WpMh2TEe2Zq6PeUF1h1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fk1aMB2TEe2Zq6PeUF1h1Q" target="_VIfMkB2SEe2Zq6PeUF1h1Q" source="_evCaoB2TEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fk_LMB2TEe2Zq6PeUF1h1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_fk_LMR2TEe2Zq6PeUF1h1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SVMw4CMJEe2iQNEGxapAdw" name="SI" target="_DPhxgB2TEe2Zq6PeUF1h1Q" source="_F5ihcCMJEe2iQNEGxapAdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SVMw4SMJEe2iQNEGxapAdw"/>
        <condition xmi:type="expression:Expression" xmi:id="_SVMw4iMJEe2iQNEGxapAdw" name="notaMayorDe7" content="notaMayorDe7" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_4mdAMCTIEe2m-7ZXPv_XKw" name="notaMayorDe7" dataType="_TiD37B2GEe2Zq6PeUF1h1Q"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AvaUACMLEe2iQNEGxapAdw" target="_TiD3xx2GEe2Zq6PeUF1h1Q" source="_mNyr8CMJEe2iQNEGxapAdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AvaUASMLEe2iQNEGxapAdw"/>
        <condition xmi:type="expression:Expression" xmi:id="_AvaUAiMLEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aRrF8CMOEe2iQNEGxapAdw" target="_kFFy8B2LEe2Zq6PeUF1h1Q" source="_oZfnYB2LEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aRrF8SMOEe2iQNEGxapAdw"/>
        <condition xmi:type="expression:Expression" xmi:id="_aRrF8iMOEe2iQNEGxapAdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fzBOoCMOEe2iQNEGxapAdw" target="_F5ihcCMJEe2iQNEGxapAdw" source="_whe-AB2SEe2Zq6PeUF1h1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fzBOoSMOEe2iQNEGxapAdw"/>
        <condition xmi:type="expression:Expression" xmi:id="_fzBOoiMOEe2iQNEGxapAdw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N3AeoCTHEe2m-7ZXPv_XKw" target="_MKq4oCTHEe2m-7ZXPv_XKw" source="_0mfk0CSTEe2m-7ZXPv_XKw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N3AeoSTHEe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_N3AeoiTHEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9iNMCTJEe2m-7ZXPv_XKw" name="NO" target="_mNyr8CMJEe2iQNEGxapAdw" source="_F5ihcCMJEe2iQNEGxapAdw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9i0QCTJEe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9i0QSTJEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MtzwACTJEe2m-7ZXPv_XKw" target="_ul1P0CTIEe2m-7ZXPv_XKw" source="_mNyr8CMJEe2iQNEGxapAdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Mt0XECTJEe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Mt0XESTJEe2m-7ZXPv_XKw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lzQKcCTJEe2m-7ZXPv_XKw" target="_0mfk0CSTEe2m-7ZXPv_XKw" source="_ul1P0CTIEe2m-7ZXPv_XKw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lzQKcSTJEe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_lzQxgCTJEe2m-7ZXPv_XKw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aaMLACTKEe2m-7ZXPv_XKw" target="_TiD3xx2GEe2Zq6PeUF1h1Q" source="_0mfk0CSTEe2m-7ZXPv_XKw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aaMyECTKEe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_aaMyESTKEe2m-7ZXPv_XKw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pGKzECTREe2m-7ZXPv_XKw" target="_mNyr8CMJEe2iQNEGxapAdw" source="_utzmcCTQEe2m-7ZXPv_XKw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pGKzESTREe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_pGLaICTREe2m-7ZXPv_XKw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u4bFkCTREe2m-7ZXPv_XKw" target="_0mfk0CSTEe2m-7ZXPv_XKw" source="_uIZW0CTREe2m-7ZXPv_XKw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u4bFkSTREe2m-7ZXPv_XKw"/>
        <condition xmi:type="expression:Expression" xmi:id="_u4bsoCTREe2m-7ZXPv_XKw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_TiD32x2GEe2Zq6PeUF1h1Q" name="Estudiente " initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_YcDTACMMEe2iQNEGxapAdw" name="Secretaria"/>
      <actors xmi:type="process:Actor" xmi:id="_cXCh4CMMEe2iQNEGxapAdw" name="Director de TIC o TT "/>
      <actors xmi:type="process:Actor" xmi:id="_gOIvQCMMEe2iQNEGxapAdw" name="Tribunal"/>
      <actors xmi:type="process:Actor" xmi:id="_iWY1MCMMEe2iQNEGxapAdw" name="Secretario Abogado"/>
      <contract xmi:type="process:Contract" xmi:id="_TiD33B2GEe2Zq6PeUF1h1Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TiD33R2GEe2Zq6PeUF1h1Q">
        <name xmi:type="expression:Expression" xmi:id="_TiD33h2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TiD33x2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TiD34B2GEe2Zq6PeUF1h1Q">
        <name xmi:type="expression:Expression" xmi:id="_TiD34R2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TiD34h2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TiD34x2GEe2Zq6PeUF1h1Q">
        <name xmi:type="expression:Expression" xmi:id="_TiD35B2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TiD35R2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TiD35h2GEe2Zq6PeUF1h1Q">
        <name xmi:type="expression:Expression" xmi:id="_TiD35x2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TiD36B2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_TiD36R2GEe2Zq6PeUF1h1Q">
        <name xmi:type="expression:Expression" xmi:id="_TiD36h2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_TiD36x2GEe2Zq6PeUF1h1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_TiD37B2GEe2Zq6PeUF1h1Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_TiD37R2GEe2Zq6PeUF1h1Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_TiD37h2GEe2Zq6PeUF1h1Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_TiD37x2GEe2Zq6PeUF1h1Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_TiD38B2GEe2Zq6PeUF1h1Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_TiD38R2GEe2Zq6PeUF1h1Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_TiD38h2GEe2Zq6PeUF1h1Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_TiD38x2GEe2Zq6PeUF1h1Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_TiD39B2GEe2Zq6PeUF1h1Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_TiD39R2GEe2Zq6PeUF1h1Q" type="Process" element="_TiD3wB2GEe2Zq6PeUF1h1Q" name="MiDiagrama1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_TiD39h2GEe2Zq6PeUF1h1Q" type="2007" element="_TiD3wR2GEe2Zq6PeUF1h1Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_TiD39x2GEe2Zq6PeUF1h1Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_TiD3-B2GEe2Zq6PeUF1h1Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_TiD3-R2GEe2Zq6PeUF1h1Q" type="3007" element="_TiD3wh2GEe2Zq6PeUF1h1Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_TiD3-h2GEe2Zq6PeUF1h1Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TiD3-x2GEe2Zq6PeUF1h1Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TiD3_B2GEe2Zq6PeUF1h1Q" type="3005" element="_TiD3xx2GEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TiD3_R2GEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TiD3_h2GEe2Zq6PeUF1h1Q" x="163" y="63" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TiD3_x2GEe2Zq6PeUF1h1Q" type="3002" element="_TiD3wx2GEe2Zq6PeUF1h1Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TiD4AB2GEe2Zq6PeUF1h1Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TiD4AR2GEe2Zq6PeUF1h1Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TiD4Ah2GEe2Zq6PeUF1h1Q" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_LvaokB2LEe2Zq6PeUF1h1Q" type="3015" element="_LvZacB2LEe2Zq6PeUF1h1Q">
              <children xmi:type="notation:DecorationNode" xmi:id="_Lvb2sB2LEe2Zq6PeUF1h1Q" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_LvbPoB2LEe2Zq6PeUF1h1Q"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_LvbPoR2LEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_LvbPoh2LEe2Zq6PeUF1h1Q"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LvbPox2LEe2Zq6PeUF1h1Q" x="384" y="10" width="283" height="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pLQbgB2LEe2Zq6PeUF1h1Q" type="3005" element="_pLNYMB2LEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pLRCkB2LEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pLQbgR2LEe2Zq6PeUF1h1Q" x="359" y="164" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mNyr_SMJEe2iQNEGxapAdw" type="3005" element="_mNyr8CMJEe2iQNEGxapAdw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mNyr_yMJEe2iQNEGxapAdw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_ut1boCTQEe2m-7ZXPv_XKw" type="3043" element="_utzmcCTQEe2m-7ZXPv_XKw" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_ut2CsCTQEe2m-7ZXPv_XKw" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_ut2CsSTQEe2m-7ZXPv_XKw" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ut1boSTQEe2m-7ZXPv_XKw" x="19" y="64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mNyr_iMJEe2iQNEGxapAdw" x="916" y="391" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0mfk3SSTEe2m-7ZXPv_XKw" type="3005" element="_0mfk0CSTEe2m-7ZXPv_XKw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0mfk3ySTEe2m-7ZXPv_XKw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_uIZ94CTREe2m-7ZXPv_XKw" type="3043" element="_uIZW0CTREe2m-7ZXPv_XKw" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_uIak8CTREe2m-7ZXPv_XKw" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_uIak8STREe2m-7ZXPv_XKw" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uIZ94STREe2m-7ZXPv_XKw"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0mfk3iSTEe2m-7ZXPv_XKw" x="1106" y="193" width="164" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MK0poCTHEe2m-7ZXPv_XKw" type="3062" element="_MKq4oCTHEe2m-7ZXPv_XKw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_MK0poiTHEe2m-7ZXPv_XKw" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MK0poyTHEe2m-7ZXPv_XKw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MK0poSTHEe2m-7ZXPv_XKw" x="1428" y="198"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_TaRS4STHEe2m-7ZXPv_XKw" type="3015" element="_TaRS4CTHEe2m-7ZXPv_XKw">
              <children xmi:type="notation:DecorationNode" xmi:id="_TaRS5iTHEe2m-7ZXPv_XKw" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_TaRS4iTHEe2m-7ZXPv_XKw"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_TaRS4yTHEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_TaRS5CTHEe2m-7ZXPv_XKw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TaRS5STHEe2m-7ZXPv_XKw" x="1229" y="98" width="162" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ul5hQCTIEe2m-7ZXPv_XKw" type="3008" element="_ul1P0CTIEe2m-7ZXPv_XKw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ul6IUCTIEe2m-7ZXPv_XKw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ul6IUSTIEe2m-7ZXPv_XKw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ul5hQSTIEe2m-7ZXPv_XKw" x="1163" y="331" width="42" height="42"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TiD4Ax2GEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TiD4BB2GEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TiD4BR2GEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TiD4Bh2GEe2Zq6PeUF1h1Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TiD4Bx2GEe2Zq6PeUF1h1Q" x="23" y="10" width="1571" height="510"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jPfkgB2HEe2Zq6PeUF1h1Q" type="3007" element="_jPVzgB2HEe2Zq6PeUF1h1Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_jPoucB2HEe2Zq6PeUF1h1Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jPoucR2HEe2Zq6PeUF1h1Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_kFI2QB2LEe2Zq6PeUF1h1Q" type="3008" element="_kFFy8B2LEe2Zq6PeUF1h1Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kFI2Qh2LEe2Zq6PeUF1h1Q" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kFJdUB2LEe2Zq6PeUF1h1Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kFI2QR2LEe2Zq6PeUF1h1Q" x="196" y="180"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oZj40B2LEe2Zq6PeUF1h1Q" type="3005" element="_oZfnYB2LEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oZkf4B2LEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oZj40R2LEe2Zq6PeUF1h1Q" x="134" y="47" width="139" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_whoH9B2SEe2Zq6PeUF1h1Q" type="3005" element="_whe-AB2SEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_whoH9h2SEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_whoH9R2SEe2Zq6PeUF1h1Q" x="856" y="157" width="165" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DPrigB2TEe2Zq6PeUF1h1Q" type="3062" element="_DPhxgB2TEe2Zq6PeUF1h1Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DPrigh2TEe2Zq6PeUF1h1Q" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DPrigx2TEe2Zq6PeUF1h1Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DPrigR2TEe2Zq6PeUF1h1Q" x="1296" y="183"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F5ihdCMJEe2iQNEGxapAdw" type="3008" element="_F5ihcCMJEe2iQNEGxapAdw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F5ihdiMJEe2iQNEGxapAdw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F5ihdyMJEe2iQNEGxapAdw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F5ihdSMJEe2iQNEGxapAdw" x="1135" y="177"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jPfkgR2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jPfkgh2HEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jPfkgx2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jPouch2HEe2Zq6PeUF1h1Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jPfkhB2HEe2Zq6PeUF1h1Q" x="23" y="284" width="1177" height="299"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jwL2wR2HEe2Zq6PeUF1h1Q" type="3007" element="_jwL2wB2HEe2Zq6PeUF1h1Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_jwL2xh2HEe2Zq6PeUF1h1Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jwL2xx2HEe2Zq6PeUF1h1Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_3aQQ3R2LEe2Zq6PeUF1h1Q" type="3005" element="_3aQQ0B2LEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3aQQ3x2LEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3aQQ3h2LEe2Zq6PeUF1h1Q" x="140" y="82" width="166" height="83"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jwL2wh2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jwL2wx2HEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jwL2xB2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jwL2yB2HEe2Zq6PeUF1h1Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jwL2xR2HEe2Zq6PeUF1h1Q" x="48" y="809" width="1571" height="225"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_2iPAgR2HEe2Zq6PeUF1h1Q" type="3007" element="_2iPAgB2HEe2Zq6PeUF1h1Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_2iPAhh2HEe2Zq6PeUF1h1Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_2iPAhx2HEe2Zq6PeUF1h1Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_FFWyHR2QEe2Zq6PeUF1h1Q" type="3005" element="_FFWyEB2QEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FFWyHx2QEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FFWyHh2QEe2Zq6PeUF1h1Q" x="151" y="133" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FefY7R2SEe2Zq6PeUF1h1Q" type="3005" element="_FefY4B2SEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FepJ4B2SEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FefY7h2SEe2Zq6PeUF1h1Q" x="460" y="135" width="170" height="85"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LVWemR2SEe2Zq6PeUF1h1Q" type="3027" element="_LVWekB2SEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_LVWemx2SEe2Zq6PeUF1h1Q" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LVWemh2SEe2Zq6PeUF1h1Q" x="707" y="134" width="151" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VIfMnR2SEe2Zq6PeUF1h1Q" type="3005" element="_VIfMkB2SEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VIfMnx2SEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VIfMnh2SEe2Zq6PeUF1h1Q" x="932" y="121" width="180" height="90"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_2iPAgh2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_2iPAgx2HEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_2iPAhB2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_2iPAiB2HEe2Zq6PeUF1h1Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2iPAhR2HEe2Zq6PeUF1h1Q" x="48" y="750" width="777" height="285"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_66wf8R2HEe2Zq6PeUF1h1Q" type="3007" element="_66wf8B2HEe2Zq6PeUF1h1Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_66wf9h2HEe2Zq6PeUF1h1Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_66wf9x2HEe2Zq6PeUF1h1Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_evCarR2TEe2Zq6PeUF1h1Q" type="3005" element="_evCaoB2TEe2Zq6PeUF1h1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_evLkkB2TEe2Zq6PeUF1h1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_evCarh2TEe2Zq6PeUF1h1Q" x="723" y="38" width="141" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_66wf8h2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_66wf8x2HEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_66wf9B2HEe2Zq6PeUF1h1Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_66wf-B2HEe2Zq6PeUF1h1Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_66wf9R2HEe2Zq6PeUF1h1Q" x="23" y="1148" width="1468" height="151"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_TiD4CB2GEe2Zq6PeUF1h1Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_TiD4CR2GEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_TiD4Ch2GEe2Zq6PeUF1h1Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_TiD4Cx2GEe2Zq6PeUF1h1Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TiD4DB2GEe2Zq6PeUF1h1Q" width="1594" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_TiNBsB2GEe2Zq6PeUF1h1Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_TiNBsR2GEe2Zq6PeUF1h1Q" type="4001" element="_TiD32B2GEe2Zq6PeUF1h1Q" source="_TiD3_x2GEe2Zq6PeUF1h1Q" target="_TiD3_B2GEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TiNBsh2GEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TiNBsx2GEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TiNBtB2GEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TiNBtR2GEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LvmOwB2LEe2Zq6PeUF1h1Q" type="4003" element="_LvkZkB2LEe2Zq6PeUF1h1Q" source="_LvaokB2LEe2Zq6PeUF1h1Q" target="_TiD3_B2GEe2Zq6PeUF1h1Q">
      <styles xmi:type="notation:FontStyle" xmi:id="_LvmOwR2LEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LvmOwh2LEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RWwEgB2LEe2Zq6PeUF1h1Q" type="4001" element="_RWlscB2LEe2Zq6PeUF1h1Q" source="_TiD3_B2GEe2Zq6PeUF1h1Q" target="_oZj40B2LEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RWygwB2LEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RWygwR2LEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RWwEgR2LEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RWwEgh2LEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_noF_oB2LEe2Zq6PeUF1h1Q" type="4001" element="_nn-D0B2LEe2Zq6PeUF1h1Q" source="_kFI2QB2LEe2Zq6PeUF1h1Q" target="_pLQbgB2LEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_noGmsB2LEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_noGmsR2LEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_noF_oR2LEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_noF_oh2LEe2Zq6PeUF1h1Q" points="[22, 0, -193, 285]$[205, 0, -10, 285]$[205, -248, -10, 37]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xOrfYx2LEe2Zq6PeUF1h1Q" type="4001" element="_xOrfYB2LEe2Zq6PeUF1h1Q" source="_pLQbgB2LEe2Zq6PeUF1h1Q" target="_TiD3_B2GEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xOrfZh2LEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xOrfZx2LEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xOrfZB2LEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xOrfZR2LEe2Zq6PeUF1h1Q" points="[-80, -28, 202, 71]$[-80, -100, 202, -1]$[-222, -100, 60, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xOwX4B2LEe2Zq6PeUF1h1Q" id="(1.0,0.3835616438356164)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_23zEAB2LEe2Zq6PeUF1h1Q" type="4001" element="_23WYEB2LEe2Zq6PeUF1h1Q" source="_kFI2QB2LEe2Zq6PeUF1h1Q" target="_3aQQ3R2LEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_23zEAx2LEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_23zEBB2LEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_23zEAR2LEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_23zEAh2LEe2Zq6PeUF1h1Q" points="[-4, 17, -10, -155]$[-4, 131, -10, -41]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QId6Mx2QEe2Zq6PeUF1h1Q" type="4001" element="_QId6MB2QEe2Zq6PeUF1h1Q" source="_FFWyHR2QEe2Zq6PeUF1h1Q" target="_FefY7R2SEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QInrMB2QEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QInrMR2QEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QId6NB2QEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QId6NR2QEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_29-80B2REe2Zq6PeUF1h1Q" type="4001" element="_291L0B2REe2Zq6PeUF1h1Q" source="_3aQQ3R2LEe2Zq6PeUF1h1Q" target="_FFWyHR2QEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_29-80x2REe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_29-81B2REe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_29-80R2REe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_29-80h2REe2Zq6PeUF1h1Q" points="[-18, 1, -30, -253]$[-18, 249, -30, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_29-81R2REe2Zq6PeUF1h1Q" id="(0.5421686746987951,0.9879518072289156)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_29-81h2REe2Zq6PeUF1h1Q" id="(0.5055555555555555,0.05555555555555555)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LVfogx2SEe2Zq6PeUF1h1Q" type="4001" element="_LVfogB2SEe2Zq6PeUF1h1Q" source="_FefY7R2SEe2Zq6PeUF1h1Q" target="_LVWemR2SEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LVfohh2SEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LVfohx2SEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LVfohB2SEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LVfohR2SEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vSpMUx2SEe2Zq6PeUF1h1Q" type="4001" element="_vSpMUB2SEe2Zq6PeUF1h1Q" source="_VIfMnR2SEe2Zq6PeUF1h1Q" target="_whoH9B2SEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vSpMVh2SEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vSpMVx2SEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vSpMVB2SEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vSpMVR2SEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Z7bhsB2TEe2Zq6PeUF1h1Q" type="4001" element="_Z7WpMB2TEe2Zq6PeUF1h1Q" source="_LVWemR2SEe2Zq6PeUF1h1Q" target="_evCarR2TEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Z7cIwB2TEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Z7cIwR2TEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Z7bhsR2TEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Z7bhsh2TEe2Zq6PeUF1h1Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fk_LMh2TEe2Zq6PeUF1h1Q" type="4001" element="_fk1aMB2TEe2Zq6PeUF1h1Q" source="_evCarR2TEe2Zq6PeUF1h1Q" target="_VIfMnR2SEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fk_LNR2TEe2Zq6PeUF1h1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fk_LNh2TEe2Zq6PeUF1h1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fk_LMx2TEe2Zq6PeUF1h1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fk_LNB2TEe2Zq6PeUF1h1Q" points="[0, 0, -118, 143]$[118, -140, 0, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fk_LNx2TEe2Zq6PeUF1h1Q" id="(1.0,0.35714285714285715)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fk_LOB2TEe2Zq6PeUF1h1Q" id="(0.55625,0.9625)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SVfr0CMJEe2iQNEGxapAdw" type="4001" element="_SVMw4CMJEe2iQNEGxapAdw" source="_F5ihdCMJEe2iQNEGxapAdw" target="_DPrigB2TEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SVfr0yMJEe2iQNEGxapAdw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SVfr1CMJEe2iQNEGxapAdw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SVfr0SMJEe2iQNEGxapAdw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SVfr0iMJEe2iQNEGxapAdw" points="[-4, -16, -183, -11]$[173, -16, -6, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SVpc0CMJEe2iQNEGxapAdw" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SVpc0SMJEe2iQNEGxapAdw" id="(0.23333333333333334,0.6333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AvaUAyMLEe2iQNEGxapAdw" type="4001" element="_AvaUACMLEe2iQNEGxapAdw" source="_mNyr_SMJEe2iQNEGxapAdw" target="_TiD3_B2GEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AvaUBiMLEe2iQNEGxapAdw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AvaUByMLEe2iQNEGxapAdw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AvaUBCMLEe2iQNEGxapAdw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AvaUBSMLEe2iQNEGxapAdw" points="[-88, -31, 696, 95]$[-88, -127, 696, -1]$[-777, -127, 7, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AvaUCCMLEe2iQNEGxapAdw" id="(1.0,0.4305555555555556)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AvaUCSMLEe2iQNEGxapAdw" id="(0.9416666666666667,0.6666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aRrF8yMOEe2iQNEGxapAdw" type="4001" element="_aRrF8CMOEe2iQNEGxapAdw" source="_oZj40B2LEe2Zq6PeUF1h1Q" target="_kFI2QB2LEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aRrF9iMOEe2iQNEGxapAdw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aRrF9yMOEe2iQNEGxapAdw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aRrF9CMOEe2iQNEGxapAdw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aRrF9SMOEe2iQNEGxapAdw" points="[-57, 34, -1, -85]$[-57, 99, -1, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aR028CMOEe2iQNEGxapAdw" id="(1.0,0.5072463768115942)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fzBOoyMOEe2iQNEGxapAdw" type="4001" element="_fzBOoCMOEe2iQNEGxapAdw" source="_whoH9B2SEe2Zq6PeUF1h1Q" target="_F5ihdCMJEe2iQNEGxapAdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fzBOpiMOEe2iQNEGxapAdw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fzBOpyMOEe2iQNEGxapAdw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fzBOpCMOEe2iQNEGxapAdw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fzBOpSMOEe2iQNEGxapAdw" points="[0, 16, -116, 6]$[115, 16, -1, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fzBOqCMOEe2iQNEGxapAdw" id="(1.0,0.32926829268292684)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fzBOqSMOEe2iQNEGxapAdw" id="(0.046511627906976744,0.3953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N3AeoyTHEe2m-7ZXPv_XKw" type="4001" element="_N3AeoCTHEe2m-7ZXPv_XKw" source="_0mfk3SSTEe2m-7ZXPv_XKw" target="_MK0poCTHEe2m-7ZXPv_XKw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N3AepiTHEe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N3AepyTHEe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N3AepCTHEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N3AepSTHEe2m-7ZXPv_XKw" points="[0, -1, -78, -5]$[74, -7, -4, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N3KPoCTHEe2m-7ZXPv_XKw" id="(1.0,0.37037037037037035)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TakN0STHEe2m-7ZXPv_XKw" type="4003" element="_TakN0CTHEe2m-7ZXPv_XKw" source="_TaRS4STHEe2m-7ZXPv_XKw" target="_0mfk3SSTEe2m-7ZXPv_XKw">
      <styles xmi:type="notation:FontStyle" xmi:id="_TakN0iTHEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TakN0yTHEe2m-7ZXPv_XKw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9tzYCTJEe2m-7ZXPv_XKw" type="4001" element="_D9iNMCTJEe2m-7ZXPv_XKw" source="_F5ihdCMJEe2iQNEGxapAdw" target="_mNyr_SMJEe2iQNEGxapAdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9w2sCTJEe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9xdwCTJEe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9tzYSTJEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9tzYiTJEe2m-7ZXPv_XKw" points="[-7, -11, 136, 205]$[-89, -215, 54, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_D99D8CTJEe2m-7ZXPv_XKw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Mt1lMCTJEe2m-7ZXPv_XKw" type="4001" element="_MtzwACTJEe2m-7ZXPv_XKw" source="_mNyr_SMJEe2iQNEGxapAdw" target="_ul5hQCTIEe2m-7ZXPv_XKw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Mt1lMyTJEe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Mt2MQCTJEe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Mt1lMSTJEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Mt1lMiTJEe2m-7ZXPv_XKw" points="[0, -10, -124, 60]$[125, -10, 1, 60]$[125, -49, 1, 21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mt52oCTJEe2m-7ZXPv_XKw" id="(1.0,0.4305555555555556)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lzR_oCTJEe2m-7ZXPv_XKw" type="4001" element="_lzQKcCTJEe2m-7ZXPv_XKw" source="_ul5hQCTIEe2m-7ZXPv_XKw" target="_0mfk3SSTEe2m-7ZXPv_XKw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lzSmsCTJEe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lzSmsSTJEe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lzR_oSTJEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lzR_oiTJEe2m-7ZXPv_XKw" points="[-23, -31, -9, 72]$[-23, -89, -9, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lzbJkCTJEe2m-7ZXPv_XKw" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lzbJkSTJEe2m-7ZXPv_XKw" id="(0.524390243902439,0.8271604938271605)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aaOAMCTKEe2m-7ZXPv_XKw" type="4001" element="_aaMLACTKEe2m-7ZXPv_XKw" source="_0mfk3SSTEe2m-7ZXPv_XKw" target="_TiD3_B2GEe2Zq6PeUF1h1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aaOnQCTKEe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aaOnQSTKEe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aaOAMSTKEe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aaOAMiTKEe2m-7ZXPv_XKw" points="[-82, -31, 927, 111]$[-82, -144, 927, -2]$[-576, -144, 433, -2]$[-576, -139, 433, 3]$[-987, -139, 22, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aaVU8CTKEe2m-7ZXPv_XKw" id="(1.0,0.38271604938271603)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aaVU8STKEe2m-7ZXPv_XKw" id="(0.8166666666666667,0.31666666666666665)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pGPEgCTREe2m-7ZXPv_XKw" type="4001" element="_pGKzECTREe2m-7ZXPv_XKw" source="_ut1boCTQEe2m-7ZXPv_XKw" target="_mNyr_SMJEe2iQNEGxapAdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pGPrkCTREe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pGPrkSTREe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pGPEgSTREe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pGPEgiTREe2m-7ZXPv_XKw" points="[0, 0, -28, 53]$[0, 20, -28, 73]$[12, 20, -16, 73]$[12, -17, -16, 36]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pGTV8CTREe2m-7ZXPv_XKw" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u4cTsCTREe2m-7ZXPv_XKw" type="4001" element="_u4bFkCTREe2m-7ZXPv_XKw" source="_uIZ94CTREe2m-7ZXPv_XKw" target="_0mfk3SSTEe2m-7ZXPv_XKw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u4c6wCTREe2m-7ZXPv_XKw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u4c6wSTREe2m-7ZXPv_XKw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u4cTsSTREe2m-7ZXPv_XKw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u4cTsiTREe2m-7ZXPv_XKw" points="[-25, 0, -78, 33]$[-25, 28, -78, 61]$[-15, 28, -68, 61]$[-15, -17, -68, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_u4kPgCTREe2m-7ZXPv_XKw" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_u4k2kCTREe2m-7ZXPv_XKw" id="(0.6402439024390244,0.8024691358024691)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
