<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_5nFPYP27EeygCqbg8F2-iA" name="PROCESO DE TIC" author="Usuario" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_5nFPYf27EeygCqbg8F2-iA" name="Nuevo Proceso de Titulación ">
      <elements xmi:type="process:Lane" xmi:id="_5nFPYv27EeygCqbg8F2-iA" name="CIS" actor="_5nFPe_27EeygCqbg8F2-iA">
        <elements xmi:type="process:StartEvent" xmi:id="_5nFPY_27EeygCqbg8F2-iA" name="inicio" outgoing="_5nFPeP27EeygCqbg8F2-iA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5nFPZP27EeygCqbg8F2-iA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5nFPZf27EeygCqbg8F2-iA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5nFPZv27EeygCqbg8F2-iA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ggTxMAjdEe2Oa_dV04Jvpg" name="¿continuar-SPr?" outgoing="_ixM1wAjdEe2Oa_dV04Jvpg _kOOX8AjeEe2Oa_dV04Jvpg" incoming="_e_VtsAjdEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ei1-8AjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ei1X4AjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ei1-8QjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_kL7uYAjdEe2Oa_dV04Jvpg" name="¿continuar-SPu?" outgoing="_l4QtUAjdEe2Oa_dV04Jvpg _jsxQsAjeEe2Oa_dV04Jvpg" incoming="_jpDq0AjdEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_joo0EQjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_joo0EAjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_joo0EgjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_g7uFYAjeEe2Oa_dV04Jvpg" name="PIC/TT no aprobado" incoming="_kOOX8AjeEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g7uscQjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g7uscAjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g7vTgAjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_ha9mIAjeEe2Oa_dV04Jvpg" name="PIC/TT abandonado" incoming="_jsxQsAjeEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ha-NMQjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ha-NMAjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ha-NMgjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_iF71wAjeEe2Oa_dV04Jvpg" name="fin de proceso PIC/TT" incoming="_i--WkAjeEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iF9D4AjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iF8c0AjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iF9D4QjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_-YWigAjeEe2Oa_dV04Jvpg" name="ELABORACIÓN Y APROBACIÓN DEL PROYECTO O PLAN" outgoing="_e_VtsAjdEe2Oa_dV04Jvpg" incoming="_5nFPeP27EeygCqbg8F2-iA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5nFPaP27EeygCqbg8F2-iA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5nFPaf27EeygCqbg8F2-iA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5nFPav27EeygCqbg8F2-iA" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_KS08QCMREe2iQNEGxapAdw" name="elaboracion" dataType="_5nFPjP27EeygCqbg8F2-iA">
            <defaultValue xmi:type="expression:Expression" xmi:id="_KS08QSMREe2iQNEGxapAdw" name="" content="" returnType="java.lang.Boolean"/>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5nFPa_27EeygCqbg8F2-iA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5nFPbP27EeygCqbg8F2-iA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5nFPbf27EeygCqbg8F2-iA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5nFPbv27EeygCqbg8F2-iA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5nFPb_27EeygCqbg8F2-iA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_-YXwoAjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_-YXwoQjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="__hR5cAjeEe2Oa_dV04Jvpg" name="EJECUCIÓN" outgoing="_jpDq0AjdEe2Oa_dV04Jvpg" incoming="_ixM1wAjdEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iwHQoAjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iwGpkAjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iwHQoQjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iwHQogjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iwHQowjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iwHQpAjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iwH3sAjdEe2Oa_dV04Jvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iwHQpQjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="__hSggwjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="__hSghAjeEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_ARZu0AjfEe2Oa_dV04Jvpg" name="PRESENTACIÓN DEL INFORME FINAL" outgoing="_i--WkAjeEe2Oa_dV04Jvpg" incoming="_l4QtUAjdEe2Oa_dV04Jvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l3f4UAjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l3fRQAjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l3f4UQjdEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_l3f4UgjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_l3f4UwjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_l3f4VAjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_l3f4VgjdEe2Oa_dV04Jvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_l3f4VQjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_ARaV4wjfEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_ARaV5AjfEe2Oa_dV04Jvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_3vHasBMQEe2ovpqI08AB_w" name="continuarpropuesta" dataType="_5nFPjP27EeygCqbg8F2-iA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_3vHasRMQEe2ovpqI08AB_w" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6-6-kBMQEe2ovpqI08AB_w" name="continuarsustentacion" dataType="_5nFPjP27EeygCqbg8F2-iA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6-6-kRMQEe2ovpqI08AB_w" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_5nFPdP27EeygCqbg8F2-iA">
        <targetForm xmi:type="expression:Expression" xmi:id="_5nFPdf27EeygCqbg8F2-iA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_5nFPdv27EeygCqbg8F2-iA">
        <targetForm xmi:type="expression:Expression" xmi:id="_5nFPd_27EeygCqbg8F2-iA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5nFPeP27EeygCqbg8F2-iA" target="_-YWigAjeEe2Oa_dV04Jvpg" source="_5nFPY_27EeygCqbg8F2-iA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5nFPef27EeygCqbg8F2-iA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5nFPev27EeygCqbg8F2-iA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_e_VtsAjdEe2Oa_dV04Jvpg" target="_ggTxMAjdEe2Oa_dV04Jvpg" source="_-YWigAjeEe2Oa_dV04Jvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_e_W70AjdEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_e_W70QjdEe2Oa_dV04Jvpg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ixM1wAjdEe2Oa_dV04Jvpg" name="SI" target="__hR5cAjeEe2Oa_dV04Jvpg" source="_ggTxMAjdEe2Oa_dV04Jvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ixNc0AjdEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ixNc0QjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jpDq0AjdEe2Oa_dV04Jvpg" target="_kL7uYAjdEe2Oa_dV04Jvpg" source="__hR5cAjeEe2Oa_dV04Jvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jpER4AjdEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_jpER4QjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l4QtUAjdEe2Oa_dV04Jvpg" name="SI" target="_ARZu0AjfEe2Oa_dV04Jvpg" source="_kL7uYAjdEe2Oa_dV04Jvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l4RUYAjdEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_l4RUYQjdEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i--WkAjeEe2Oa_dV04Jvpg" target="_iF71wAjeEe2Oa_dV04Jvpg" source="_ARZu0AjfEe2Oa_dV04Jvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i--9oAjeEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_i--9oQjeEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jsxQsAjeEe2Oa_dV04Jvpg" name="NO" target="_ha9mIAjeEe2Oa_dV04Jvpg" source="_kL7uYAjdEe2Oa_dV04Jvpg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jsxQsQjeEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_jsxQsgjeEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kOOX8AjeEe2Oa_dV04Jvpg" name="NO" target="_g7uFYAjeEe2Oa_dV04Jvpg" source="_ggTxMAjdEe2Oa_dV04Jvpg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kOO_AAjeEe2Oa_dV04Jvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_kOO_AQjeEe2Oa_dV04Jvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_5nFPe_27EeygCqbg8F2-iA" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_5nFPfP27EeygCqbg8F2-iA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5nFPff27EeygCqbg8F2-iA">
        <name xmi:type="expression:Expression" xmi:id="_5nFPfv27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5nFPf_27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5nFPgP27EeygCqbg8F2-iA">
        <name xmi:type="expression:Expression" xmi:id="_5nFPgf27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5nFPgv27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5nFPg_27EeygCqbg8F2-iA">
        <name xmi:type="expression:Expression" xmi:id="_5nFPhP27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5nFPhf27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5nFPhv27EeygCqbg8F2-iA">
        <name xmi:type="expression:Expression" xmi:id="_5nFPh_27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5nFPiP27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5nFPif27EeygCqbg8F2-iA">
        <name xmi:type="expression:Expression" xmi:id="_5nFPiv27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5nFPi_27EeygCqbg8F2-iA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_5nFPjP27EeygCqbg8F2-iA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_5nFPjf27EeygCqbg8F2-iA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_5nFPjv27EeygCqbg8F2-iA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_5nFPj_27EeygCqbg8F2-iA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_5nFPkP27EeygCqbg8F2-iA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_5nFPkf27EeygCqbg8F2-iA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_5nFPkv27EeygCqbg8F2-iA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_5nFPk_27EeygCqbg8F2-iA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_5nFPlP27EeygCqbg8F2-iA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_5nFPlf27EeygCqbg8F2-iA" type="Process" element="_5nFPYP27EeygCqbg8F2-iA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_5nFPlv27EeygCqbg8F2-iA" type="2007" element="_5nFPYf27EeygCqbg8F2-iA">
      <children xmi:type="notation:DecorationNode" xmi:id="_5nFPl_27EeygCqbg8F2-iA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_5nFPmP27EeygCqbg8F2-iA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_5nFPmf27EeygCqbg8F2-iA" type="3007" element="_5nFPYv27EeygCqbg8F2-iA">
          <children xmi:type="notation:DecorationNode" xmi:id="_5nFPmv27EeygCqbg8F2-iA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_5nFPm_27EeygCqbg8F2-iA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_5nFPn_27EeygCqbg8F2-iA" type="3002" element="_5nFPY_27EeygCqbg8F2-iA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5nFPoP27EeygCqbg8F2-iA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5nFPof27EeygCqbg8F2-iA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5nFPov27EeygCqbg8F2-iA" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ggYCoAjdEe2Oa_dV04Jvpg" type="3008" element="_ggTxMAjdEe2Oa_dV04Jvpg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gg8qYAjdEe2Oa_dV04Jvpg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gg9RcAjdEe2Oa_dV04Jvpg" x="1" y="-53"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ggYCoQjdEe2Oa_dV04Jvpg" x="365" y="71" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kL-xsAjdEe2Oa_dV04Jvpg" type="3008" element="_kL7uYAjdEe2Oa_dV04Jvpg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kL_YwAjdEe2Oa_dV04Jvpg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kL_YwQjdEe2Oa_dV04Jvpg" y="-53"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kL-xsQjdEe2Oa_dV04Jvpg" x="669" y="76" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_g7yW0AjeEe2Oa_dV04Jvpg" type="3062" element="_g7uFYAjeEe2Oa_dV04Jvpg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_g7zk8AjeEe2Oa_dV04Jvpg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_g7zk8QjeEe2Oa_dV04Jvpg" x="8" y="19"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g7yW0QjeEe2Oa_dV04Jvpg" x="372" y="169"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ha_bUAjeEe2Oa_dV04Jvpg" type="3062" element="_ha9mIAjeEe2Oa_dV04Jvpg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hbACYAjeEe2Oa_dV04Jvpg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hbACYQjeEe2Oa_dV04Jvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ha_bUQjeEe2Oa_dV04Jvpg" x="676" y="167"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iF-5EAjeEe2Oa_dV04Jvpg" type="3062" element="_iF71wAjeEe2Oa_dV04Jvpg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_iF_gIAjeEe2Oa_dV04Jvpg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iF_gIQjeEe2Oa_dV04Jvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iF-5EQjeEe2Oa_dV04Jvpg" x="1030" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-YY-wAjeEe2Oa_dV04Jvpg" type="3063" element="_-YWigAjeEe2Oa_dV04Jvpg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-YZl0AjeEe2Oa_dV04Jvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-YY-wQjeEe2Oa_dV04Jvpg" x="160" y="60" width="164" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__hTHkQjeEe2Oa_dV04Jvpg" type="3063" element="__hR5cAjeEe2Oa_dV04Jvpg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__hTuoAjeEe2Oa_dV04Jvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__hTHkgjeEe2Oa_dV04Jvpg" x="442" y="62" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ARa88wjfEe2Oa_dV04Jvpg" type="3063" element="_ARZu0AjfEe2Oa_dV04Jvpg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ARbkAAjfEe2Oa_dV04Jvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ARa89AjfEe2Oa_dV04Jvpg" x="764" y="58" width="178" height="89"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_5nFPo_27EeygCqbg8F2-iA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_5nFPpP27EeygCqbg8F2-iA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_5nFPpf27EeygCqbg8F2-iA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_5nFPpv27EeygCqbg8F2-iA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5nFPp_27EeygCqbg8F2-iA" x="23" y="10" width="1075" height="288"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_5nFPqP27EeygCqbg8F2-iA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_5nFPqf27EeygCqbg8F2-iA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_5nFPqv27EeygCqbg8F2-iA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_5nFPq_27EeygCqbg8F2-iA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5nFPrP27EeygCqbg8F2-iA" width="1193" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_5nFPrf27EeygCqbg8F2-iA"/>
    <edges xmi:type="notation:Connector" xmi:id="_5nFPrv27EeygCqbg8F2-iA" type="4001" element="_5nFPeP27EeygCqbg8F2-iA" source="_5nFPn_27EeygCqbg8F2-iA" target="_-YY-wAjeEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5nFPr_27EeygCqbg8F2-iA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5nFPsP27EeygCqbg8F2-iA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5nFPsf27EeygCqbg8F2-iA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5nFPsv27EeygCqbg8F2-iA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_e_bNQAjdEe2Oa_dV04Jvpg" type="4001" element="_e_VtsAjdEe2Oa_dV04Jvpg" source="_-YY-wAjeEe2Oa_dV04Jvpg" target="_ggYCoAjdEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_e_dpgAjdEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_e_eQkAjdEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_e_b0UAjdEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_e_b0UQjdEe2Oa_dV04Jvpg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iyTpAAjdEe2Oa_dV04Jvpg" type="4001" element="_ixM1wAjdEe2Oa_dV04Jvpg" source="_ggYCoAjdEe2Oa_dV04Jvpg" target="__hTHkQjeEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iyVeMAjdEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iyVeMQjdEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iyTpAQjdEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iyTpAgjdEe2Oa_dV04Jvpg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jpGuIAjdEe2Oa_dV04Jvpg" type="4001" element="_jpDq0AjdEe2Oa_dV04Jvpg" source="__hTHkQjeEe2Oa_dV04Jvpg" target="_kL-xsAjdEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jpH8QAjdEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jpIjUAjdEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jpGuIQjdEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jpGuIgjdEe2Oa_dV04Jvpg" points="[50, -1, -92, 0]$[121, -1, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l4TwoAjdEe2Oa_dV04Jvpg" type="4001" element="_l4QtUAjdEe2Oa_dV04Jvpg" source="_kL-xsAjdEe2Oa_dV04Jvpg" target="_ARa88wjfEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l4YCEAjdEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l4YCEQjdEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l4TwoQjdEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l4TwogjdEe2Oa_dV04Jvpg" points="[19, -2, -124, -1]$[93, -2, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i_BZ4AjeEe2Oa_dV04Jvpg" type="4001" element="_i--WkAjeEe2Oa_dV04Jvpg" source="_ARa88wjfEe2Oa_dV04Jvpg" target="_iF-5EAjeEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i_CA8AjeEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i_CA8QjeEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i_BZ4QjeEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i_BZ4gjeEe2Oa_dV04Jvpg" points="[0, 8, -103, 7]$[89, 8, -14, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i_IuoAjeEe2Oa_dV04Jvpg" id="(1.0,0.37142857142857144)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jtCWcAjeEe2Oa_dV04Jvpg" type="4001" element="_jsxQsAjeEe2Oa_dV04Jvpg" source="_kL-xsAjdEe2Oa_dV04Jvpg" target="_ha_bUAjeEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jtDkkAjeEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jtELoAjeEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jtCWcQjeEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jtCWcgjeEe2Oa_dV04Jvpg" points="[-22, 18, -1, -107]$[-22, 110, -1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jtKSQAjeEe2Oa_dV04Jvpg" id="(1.0,0.5813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kOgr0AjeEe2Oa_dV04Jvpg" type="4001" element="_kOOX8AjeEe2Oa_dV04Jvpg" source="_ggYCoAjdEe2Oa_dV04Jvpg" target="_g7yW0AjeEe2Oa_dV04Jvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kOh58AjeEe2Oa_dV04Jvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kOh58QjeEe2Oa_dV04Jvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kOgr0QjeEe2Oa_dV04Jvpg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kOgr0gjeEe2Oa_dV04Jvpg" points="[-20, 15, -7, -85]$[-18, 102, -5, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kOp1wAjeEe2Oa_dV04Jvpg" id="(1.0,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kOqc0AjeEe2Oa_dV04Jvpg" id="(0.1,0.23333333333333334)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
